### ISSUE TITLE
 Suite setup fails with "java.lang.NullPointerException, Exiting due to uncaught exception"

### ISSUE THREAD

**Issue by aravi5** [mapr/drill-test-framework#545]
When going through the code, I noticed a warning in `getTestDefinitionList` in `Utils.java`.
```
Dereference of 'root.listFiles()' may produce 'java.lang.NullPointerException'
```
I tried to reproduce the issue, to see if this warning can be ignored. Turns out this is easily reproducible. Consider the possibility that `DRILL_TEST_DATA_DIR` is configured wrongly in `drillTestConfig.properties` -
```
DRILL_TEST_DATA_DIR=framework/framework/resources
```
Results in the following error -
```
Exiting due to uncaught exception
java.lang.NullPointerException
	at org.apache.drill.test.framework.Utils.getTestDefinitionList(Utils.java:346)
	at org.apache.drill.test.framework.Utils.getTestDefSources(Utils.java:197)
	at org.apache.drill.test.framework.Utils.getDrillTestCases(Utils.java:227)
	at org.apache.drill.test.framework.TestDriver.runTests(TestDriver.java:174)
	at org.apache.drill.test.framework.TestDriver.main(TestDriver.java:93)
```

**Comment by aravi5** [comment]
The changes for this issue has been merged. Closing the issue as resolved.
